# Generated by Django 4.0.1 on 2022-01-07 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_alter_player_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='session_at',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
        ),
        migrations.AlterField(
            model_name='player',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
