# Generated by Django 4.0.1 on 2022-01-07 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_gamesession_admin_alter_player_session_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
