# Generated by Django 4.0.1 on 2022-01-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='session_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
        ),
    ]
